import type { Patient, Pregnancy, Visit } from "./types";
import { classifyRiskLevel } from "./symptom-checklist";

export const SEED_PATIENTS: Patient[] = [
  {
    id: "patient-uwimana",
    nationalId: "1198780012345678",
    firstName: "Aline",
    lastName: "Uwimana",
    dateOfBirth: "1998-03-14",
    phone: "+250788111222",
    address: { district: "Bugesera", sector: "Nyamata", cell: "Kanazi", village: "Kanazi I" },
    emergencyContact: { name: "Jean Uwimana", relationship: "Husband", phone: "+250788111223" },
    bloodGroup: "O",
    rhFactor: "positive",
    chronicConditions: [],
    registeredAt: "2026-04-12",
    registeredBy: "Nurse Uwase",
    registrationFacility: "Nyamata Health Center",
  },
  {
    id: "patient-mukeshimana",
    nationalId: "1207780023456789",
    firstName: "Claudine",
    lastName: "Mukeshimana",
    dateOfBirth: "2007-08-02",
    phone: "+250788222333",
    address: { district: "Bugesera", sector: "Nyamata", cell: "Rilima", village: "Rilima II" },
    emergencyContact: { name: "Agnes Mukeshimana", relationship: "Mother", phone: "+250788222334" },
    chronicConditions: ["Hypertension"],
    registeredAt: "2026-05-02",
    registeredBy: "Nurse Uwase",
    registrationFacility: "Nyamata Health Center",
  },
  {
    id: "patient-ingabire",
    nationalId: "1191780034567890",
    firstName: "Solange",
    lastName: "Ingabire",
    dateOfBirth: "1991-11-20",
    phone: "+250788333444",
    address: { district: "Bugesera", sector: "Nyamata", cell: "Kanazi", village: "Kanazi II" },
    emergencyContact: { name: "Eric Ingabire", relationship: "Husband", phone: "+250788333445" },
    bloodGroup: "A",
    rhFactor: "negative",
    chronicConditions: [],
    registeredAt: "2026-05-20",
    registeredBy: "Nurse Uwase",
    registrationFacility: "Nyamata Health Center",
  },
  {
    id: "patient-nyiraneza",
    nationalId: "1195780045678901",
    firstName: "Beatrice",
    lastName: "Nyiraneza",
    dateOfBirth: "1995-06-09",
    phone: "+250788444555",
    address: { district: "Bugesera", sector: "Nyamata", cell: "Rilima", village: "Rilima I" },
    emergencyContact: { name: "Marie Nyiraneza", relationship: "Sister", phone: "+250788444556" },
    allergies: "Penicillin",
    chronicConditions: [],
    registeredAt: "2026-05-28",
    registeredBy: "Nurse Uwase",
    registrationFacility: "Nyamata Health Center",
  },
];

export const SEED_PREGNANCIES: Pregnancy[] = [
  {
    id: "pregnancy-uwimana-1",
    patientId: "patient-uwimana",
    pregnancyNumber: 1,
    gravidity: 2,
    parity: 1,
    previousCS: 0,
    previousPPH: true,
    previousEclampsia: false,
    previousStillbirth: false,
    lmpDate: "2025-11-10",
    eddDate: "2026-08-17",
    startDate: "2025-11-10",
    status: "open",
    createdAt: "2026-04-12T09:00:00.000Z",
  },
  {
    id: "pregnancy-mukeshimana-1",
    patientId: "patient-mukeshimana",
    pregnancyNumber: 1,
    gravidity: 1,
    parity: 0,
    previousCS: 0,
    previousPPH: false,
    previousEclampsia: false,
    previousStillbirth: false,
    lmpDate: "2025-12-15",
    eddDate: "2026-09-21",
    startDate: "2025-12-15",
    status: "open",
    createdAt: "2026-05-02T09:00:00.000Z",
  },
  {
    id: "pregnancy-ingabire-1",
    patientId: "patient-ingabire",
    pregnancyNumber: 3,
    gravidity: 3,
    parity: 2,
    previousCS: 0,
    previousPPH: false,
    previousEclampsia: false,
    previousStillbirth: false,
    lmpDate: "2026-01-05",
    eddDate: "2026-10-12",
    startDate: "2026-01-05",
    status: "open",
    createdAt: "2026-05-20T09:00:00.000Z",
  },
  {
    id: "pregnancy-nyiraneza-1",
    patientId: "patient-nyiraneza",
    pregnancyNumber: 4,
    gravidity: 4,
    parity: 3,
    previousCS: 0,
    previousPPH: true,
    previousEclampsia: false,
    previousStillbirth: false,
    lmpDate: "2025-10-20",
    eddDate: "2026-07-27",
    startDate: "2025-10-20",
    status: "open",
    createdAt: "2026-05-28T09:00:00.000Z",
  },
];

function buildVisit(
  id: string,
  pregnancyId: string,
  date: string,
  scheduledWeek: number,
  symptomIds: string[],
  notes: string,
): Visit {
  return {
    id,
    pregnancyId,
    date,
    type: "scheduled",
    scheduledWeek,
    hospital: "Nyamata Health Center",
    attendingNurse: "Nurse Uwase",
    symptomIds,
    riskLevel: classifyRiskLevel(symptomIds),
    notes,
  };
}

export const SEED_VISITS: Visit[] = [
  buildVisit("visit-uwimana-1", "pregnancy-uwimana-1", "2026-06-10", 28, ["prev-pph"], "Routine ANC visit, monitoring for recurrence given history."),
  buildVisit("visit-mukeshimana-1", "pregnancy-mukeshimana-1", "2026-06-15", 28, ["teenage", "controlled-htn"], "Blood pressure stable on current medication."),
  buildVisit("visit-ingabire-1", "pregnancy-ingabire-1", "2026-06-20", 20, ["multiple-gestation"], "Twin pregnancy confirmed on ultrasound, growth tracking normally."),
  buildVisit("visit-nyiraneza-1", "pregnancy-nyiraneza-1", "2026-06-05", 32, ["prev-pph"], "Routine ANC visit, flagged for history of postpartum hemorrhage."),
  buildVisit("visit-nyiraneza-2", "pregnancy-nyiraneza-1", "2026-06-29", 36, ["severe-anemia", "prev-pph"], "Hb dropped to 6.4 g/dl, referred for urgent management."),
];
